/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decisionmatrice;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Winsido
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    Statement stmt;
    DBConnect con = new DBConnect();
    public RegistrationForm() {
        addMouseListener(new MouseAdapter(){
        public void mousePressed(MouseEvent e){
        }
        });
        initComponents();
        Color blu = new Color(118,149,140);
        setBackground(blu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Singup = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailFeild = new javax.swing.JTextField();
        usernameFeild = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        signUp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        passwordFeild = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        WarningMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(79, 1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(118, 149, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 42, 42));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Singup.setBackground(new java.awt.Color(204, 204, 204));
        Singup.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Singup.setForeground(new java.awt.Color(204, 204, 204));
        Singup.setText(" Sign Up");
        jPanel2.add(Singup, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("USERNAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("PASSWORD");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("EMAIL");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        emailFeild.setBackground(new java.awt.Color(42, 42, 42));
        emailFeild.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        emailFeild.setForeground(new java.awt.Color(204, 204, 204));
        emailFeild.setText("Your email here");
        emailFeild.setBorder(null);
        emailFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFeildFocusGained(evt);
            }
        });
        emailFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFeildActionPerformed(evt);
            }
        });
        jPanel2.add(emailFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 440, 40));

        usernameFeild.setBackground(new java.awt.Color(42, 42, 42));
        usernameFeild.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        usernameFeild.setForeground(new java.awt.Color(204, 204, 204));
        usernameFeild.setText("Enter your username");
        usernameFeild.setBorder(null);
        usernameFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameFeildMouseClicked(evt);
            }
        });
        usernameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFeildActionPerformed(evt);
            }
        });
        jPanel2.add(usernameFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 440, 40));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 440, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 440, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 440, 10));

        jCheckBox1.setBackground(new java.awt.Color(47, 44, 44));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("I agree all terms of service");
        jCheckBox1.setBorder(null);
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        signUp.setBackground(new java.awt.Color(118, 149, 140));
        signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signUpMousePressed(evt);
            }
        });
        signUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Sign Up");
        signUp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, 50));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Sign Up");
        signUp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, -1));

        jPanel2.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 150, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Already a member");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, -1, 20));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 110, 10));

        passwordFeild.setBackground(new java.awt.Color(42, 42, 42));
        passwordFeild.setForeground(new java.awt.Color(255, 255, 255));
        passwordFeild.setText("jPasswordField1");
        passwordFeild.setBorder(null);
        passwordFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFeildFocusGained(evt);
            }
        });
        passwordFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFeildActionPerformed(evt);
            }
        });
        jPanel2.add(passwordFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 440, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Make your own decisions");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 50));

        WarningMessage.setForeground(new java.awt.Color(251, 0, 0));
        jPanel2.add(WarningMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 380, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 500, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 780, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFeildActionPerformed

    private void usernameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFeildActionPerformed

    private void passwordFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFeildFocusGained
        // TODO add your handling code here:
        passwordFeild.setText("");
    }//GEN-LAST:event_passwordFeildFocusGained

    private void passwordFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFeildActionPerformed

    private void signUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMousePressed
        // TODO add your handling code here:
String username = usernameFeild.getText();
String password = passwordFeild.getText();
String email = emailFeild.getText();
//check if there is another UserName or Email
String query2="Select count(UserName)as nbuser from users where Username='"+username+"'";
String query3="Select count(Email) as nbemail from users where Email='"+email+"'";
String query = "INSERT INTO users (UserName,pass,Email) VALUES ('"+username+"','"+password+"','"+email+"')";
System.out.println(query2);
try{
   ResultSet NumberOfUsernamequerry = con.getData(query2);
  
  int NumberUser = NumberOfUsernamequerry.getInt("nbuser");
  
  

    System.out.println(NumberUser);
     ResultSet NumberOfEmailquerry = con.getData(query3);
  int NumberEmail = NumberOfEmailquerry.getInt("nbemail");
    System.out.println(NumberEmail);
    
    
    
  
    if(NumberEmail > 0 || NumberUser > 0)
        { 
            WarningMessage.setText("You are alredy a member");
            
            
        }
    else
        {
            con.setData(query);
            Singup.setText("Registration complete");
            loginOrRegistration l = new loginOrRegistration();
            l.setVisible(true);
            this.setVisible(false);
        }
   
    
   
        

    }//GEN-LAST:event_signUpMousePressed
catch(Exception ex){
   
    System.err.println(ex);
}

}

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        loginOrRegistration goToLogin = new loginOrRegistration();
        goToLogin.setVisible(true);
        this.setVisible(false);
             

    }//GEN-LAST:event_jLabel7MousePressed

    private void usernameFeildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFeildMouseClicked
        // TODO add your handling code here:
        usernameFeild.setText("");
    }//GEN-LAST:event_usernameFeildMouseClicked

    private void emailFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFeildFocusGained
        // TODO add your handling code here:
        emailFeild.setText("");
    }//GEN-LAST:event_emailFeildFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Singup;
    private javax.swing.JLabel WarningMessage;
    private javax.swing.JTextField emailFeild;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPasswordField passwordFeild;
    private javax.swing.JPanel signUp;
    private javax.swing.JTextField usernameFeild;
    // End of variables declaration//GEN-END:variables
}
